# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSuumoazabu():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_suumoazabu(self):
    self.driver.get("https://suumo.jp/jj/chintai/kensaku/FR301FB036/?ar=010&bs=040&ra=001&ek=00790&ts=2&et=5&cn=0")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.ID, "souba_ts1").click()
    self.driver.find_element(By.NAME, "et").click()
    dropdown = self.driver.find_element(By.NAME, "et")
    dropdown.find_element(By.XPATH, "//option[. = '5分～10分']").click()
    self.driver.find_element(By.NAME, "cn").click()
    dropdown = self.driver.find_element(By.NAME, "cn")
    dropdown.find_element(By.XPATH, "//option[. = '0年～5年']").click()
    self.driver.find_element(By.LINK_TEXT, "相場情報を更新する").click()
    self.driver.find_element(By.LINK_TEXT, "麻生駅の全物件一覧を見る").click()
    self.driver.find_element(By.ID, "js-tabmenu1-pcChange").click()
    dropdown = self.driver.find_element(By.ID, "js-tabmenu1-pcChange")
    dropdown.find_element(By.XPATH, "//option[. = '50件']").click()
    self.driver.execute_script("window.scrollTo(0,256)")
  
